### ISSUE TITLE
WHMCS can't connect if SSL-Cert missmatches

### ISSUE THREAD

**Issue by tobiasoitzinger** [plesk/SolusVM-WHMCS-Module#29]
When you try to connect to SolusVM which has **no valid** ssl certificate, the plugin doesn't work, because CURL verifies host and peer Certificate. 

To fix this i added:
curl_setopt($this->curl, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($this->curl, CURLOPT_SSL_VERIFYPEER, 0);

into "lib/Curl.php" inside 
 public function call()
    {
        **curl_setopt($this->curl, CURLOPT_SSL_VERIFYHOST, 0);**
        **curl_setopt($this->curl, CURLOPT_SSL_VERIFYPEER, 0);**
        $args = func_get_args();
        $function = array_shift($args);
        if (is_callable($function)) {
            array_unshift($args, $this);
            call_user_func_array($function, $args);
        }
    }

..is there any other way to archive this? Or can you add this to your Code?

**Comment by cammackmatthew** [comment]
Adding the following into the 'Access Hash' box under 'Server Details' within WHMCS when editing the server would achieve this. 

```
<ssl_verifypeer>no</ssl_verifypeer>
<ssl_verifyhost>no</ssl_verifyhost>
```

As per the SolusVM WHMCS Module docs here: https://docs.solusvm.com/display/DOCS/SSL+Configuration
